name: Deploy Google Maps to Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Inject Google Maps API Key
        run: |
          echo "Starting Google Maps API key injection..."
          if [ -z "$GOOGLE_MAPS_KEY" ]; then
            echo "Error: GOOGLE_MAPS_KEY is empty"
            exit 1
          fi
          
          echo "GOOGLE_MAPS_KEY is set (length: ${#GOOGLE_MAPS_KEY})"
          
          # Google Maps API 키 치환
          sed -i "s|__GOOGLE_MAPS_KEY__|${GOOGLE_MAPS_KEY}|g" index.html
          
          # 치환 결과 확인
          if grep -q "__GOOGLE_MAPS_KEY__" index.html; then
            echo "Error: Placeholder replacement failed"
            exit 1
          else
            echo "Success: Google Maps API key injected successfully"
          fi
        env:
          GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

